#!/usr/bin/env bash
# Provision an OAuth2 / OpenID Connect client in OpenEMR for the Patient
# Dashboard, then write the credentials into .env.local.
#
# Why dynamic registration over admin-UI clicks:
#   OpenEMR's /oauth2/default/registration endpoint implements RFC 7591
#   Dynamic Client Registration. It accepts a JSON metadata document and
#   returns a fresh client_id and client_secret. No clicks. The returned
#   client is created in the "disabled" state by default; an admin must
#   enable it once via interface/admin/oauth2_admin.php. We surface that
#   step at the end with a clickable URL.
#
# Why a confidential client (with client_secret) and not a public PKCE
# client: the dashboard runs server-side. Storing a long-lived secret in
# .env.local is safer than relying on PKCE alone for refresh tokens. We
# still use PKCE on the auth code exchange (Auth.js handles that).
#
# Failure modes are surfaced explicitly so a wrong env or unreachable
# OpenEMR is diagnosable from one log line.

set -euo pipefail

OPENEMR_BASE="${OPENEMR_BASE:-https://localhost:9300}"
DASHBOARD_URL="${DASHBOARD_URL:-http://localhost:8400}"
ENV_FILE="${ENV_FILE:-.env.local}"

CLIENT_NAME="${CLIENT_NAME:-Patient Dashboard (Local Dev)}"

REGISTRATION_URL="${OPENEMR_BASE%/}/oauth2/default/registration"

echo "→ Registering OAuth client at ${REGISTRATION_URL}"
echo "  redirect URI: ${DASHBOARD_URL%/}/api/auth/callback/openemr"
echo

#
# OpenEMR's AuthorizationController treats application_type === "private" as
# the signal to mint a client_secret. Sending "web" would create a public
# client (PKCE-only) and OpenEMR would refuse user/* scopes ("system and
# user scopes are only allowed for confidential clients"). Use "private".
#
PAYLOAD=$(cat <<EOF
{
  "application_type": "private",
  "client_name": "${CLIENT_NAME}",
  "redirect_uris": ["${DASHBOARD_URL%/}/api/auth/callback/openemr"],
  "post_logout_redirect_uris": ["${DASHBOARD_URL%/}/login"],
  "token_endpoint_auth_method": "client_secret_post",
  "grant_types": ["authorization_code", "refresh_token"],
  "response_types": ["code"],
  "scope": "openid profile fhirUser offline_access user/Patient.read user/Condition.read user/MedicationRequest.read user/AllergyIntolerance.read user/Observation.read user/Encounter.read user/CareTeam.read user/Practitioner.read",
  "initiate_login_uri": "${DASHBOARD_URL%/}/login",
  "contacts": ["dashboard@example.org"]
}
EOF
)

if ! command -v curl >/dev/null 2>&1; then
  echo "ERROR: curl not found. Install curl and retry." >&2
  exit 2
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "ERROR: jq not found. Install jq (brew install jq) and retry." >&2
  exit 2
fi

RESPONSE=$(curl --silent --show-error --fail-with-body \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Accept: application/json" \
  --data "${PAYLOAD}" \
  "${REGISTRATION_URL}") || {
    echo
    echo "ERROR: Dynamic registration failed." >&2
    echo "  endpoint: ${REGISTRATION_URL}" >&2
    echo "  response: ${RESPONSE:-<empty>}" >&2
    echo >&2
    echo "Common causes:" >&2
    echo "  - OpenEMR not reachable (start docker/development-easy)" >&2
    echo "  - Dynamic registration disabled in admin (Globals > " >&2
    echo "    'Connectors' > 'Allow OAuth Client Registration')" >&2
    echo "  - The /registration endpoint differs on your OpenEMR " >&2
    echo "    version; try ${OPENEMR_BASE%/}/oauth2/default/registration" >&2
    exit 1
}

CLIENT_ID=$(echo "${RESPONSE}" | jq -r '.client_id // empty')
CLIENT_SECRET=$(echo "${RESPONSE}" | jq -r '.client_secret // empty')

if [[ -z "${CLIENT_ID}" || -z "${CLIENT_SECRET}" ]]; then
  echo "ERROR: registration response missing client_id or client_secret." >&2
  echo "Full response:" >&2
  echo "${RESPONSE}" | jq . >&2
  exit 1
fi

echo "✓ Registered."
echo "  client_id:     ${CLIENT_ID}"
echo "  client_secret: $(printf '%s' "${CLIENT_SECRET}" | head -c 6)…"
echo

# Generate AUTH_SECRET if missing.
AUTH_SECRET="${AUTH_SECRET:-$(openssl rand -hex 32)}"

if [[ -f "${ENV_FILE}" ]]; then
  cp "${ENV_FILE}" "${ENV_FILE}.bak.$(date +%s)"
  echo "→ Backed up existing ${ENV_FILE} to ${ENV_FILE}.bak.<ts>"
fi

cat > "${ENV_FILE}" <<EOF
# Generated by scripts/register-oauth-client.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Do NOT commit this file.

OPENEMR_ISSUER=${OPENEMR_BASE%/}/oauth2/default
OPENEMR_CLIENT_ID=${CLIENT_ID}
OPENEMR_CLIENT_SECRET=${CLIENT_SECRET}
OPENEMR_FHIR_BASE=${OPENEMR_BASE%/}/apis/default/fhir/
OPENEMR_FHIR_VERIFY_SSL=1

AUTH_SECRET=${AUTH_SECRET}
AUTH_URL=${DASHBOARD_URL%/}
AUTH_TRUST_HOST=1
EOF

chmod 600 "${ENV_FILE}"
echo "✓ Wrote ${ENV_FILE} (mode 0600)."
echo

# ─── Auto-enable the client if we can reach the OpenEMR mariadb ──────────
#
# OpenEMR registers every dynamic client with is_enabled = 0. The admin
# UI flips that flag with a button click. When this script is run on the
# same host as the docker stack, we can flip it ourselves with one SQL
# update — no admin click required.
#
# If the docker exec fails (script run from a remote host, container
# named differently), we fall back to printing the admin URL.
OPENEMR_CONTAINER="${OPENEMR_CONTAINER:-development-easy-openemr-1}"
if docker exec "${OPENEMR_CONTAINER}" mariadb -h mysql -uopenemr -popenemr -Dopenemr \
    -e "UPDATE oauth_clients SET is_enabled = 1 WHERE client_id = '${CLIENT_ID}';" \
    >/dev/null 2>&1; then
  echo "✓ Auto-enabled the client (UPDATE oauth_clients SET is_enabled = 1)."
  echo
  echo "Boot the dashboard:"
  echo "    npm run dev          # http://localhost:3000"
  echo "    docker compose up    # http://localhost:8400"
else
  ENABLE_URL="${OPENEMR_BASE%/}/interface/admin/oauth2_admin.php"
  echo "→ Could not auto-enable via docker. Open this URL and click 'Enable Client':"
  echo
  echo "    ${ENABLE_URL}"
  echo
  echo "Sign in as 'admin', find the row with client name '${CLIENT_NAME}',"
  echo "click 'Enable Client', then run 'npm run dev'."
fi
